# Generated by Django 5.1.4 on 2024-12-31 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('master', 'Master Kullanıcı'), ('secretary', 'Sekreter')], default='master', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta Adresi')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Soyad')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Telefon Numarası')),
                ('membership_type', models.CharField(choices=[('standard', 'Başlangıç'), ('premium', 'Gümüş'), ('pro', 'Altın'), ('enterprise', 'Öğrenci')], default='standard', max_length=15, verbose_name='Üyelik Tipi')),
                ('membership_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_membership_approved', models.BooleanField(default=False, help_text='Yönetici onayı gerektiren üyelikler için.', verbose_name='Üyelik Onayı')),
                ('requested_membership_type', models.CharField(blank=True, choices=[('standard', 'Başlangıç'), ('premium', 'Gümüş'), ('pro', 'Altın'), ('enterprise', 'Öğrenci')], max_length=50, null=True)),
                ('requested_duration', models.CharField(blank=True, choices=[('monthly', '1 Ay'), ('yearly', '1 Yıl')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personel')),
                ('email_notifications_enabled', models.BooleanField(default=False, verbose_name='Email Bildirimlerini Aç/Kapat')),
                ('email_sending_disabled', models.BooleanField(default=True, verbose_name='Yarın Not olmasa bile E-posta gönderilsin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
