# Generated by Django 5.1.4 on 2024-12-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Email Bildirimlerini Aç/Kapat'),
        ),
    ]
