# Generated by Django 5.1.4 on 2024-12-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
