# Generated by Django 5.1.4 on 2024-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_membership_type',
            field=models.CharField(blank=True, choices=[('standard', 'Başlangıç'), ('premium', 'Gümüş'), ('pro', 'Altın'), ('enterprise', 'Öğrenci')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.CharField(choices=[('standard', 'Başlangıç'), ('premium', 'Gümüş'), ('pro', 'Altın'), ('enterprise', 'Öğrenci')], default='standard', max_length=15, verbose_name='Üyelik Tipi'),
        ),
    ]
