# Generated by Django 5.1.4 on 2024-12-31 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretary',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
