# Generated by Django 5.1.4 on 2024-12-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_enabled',
        ),
    ]
