# Generated by Django 5.1.4 on 2024-12-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_requested_membership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_duration',
            field=models.CharField(blank=True, choices=[('monthly', '1 Ay'), ('yearly', '1 Yıl')], max_length=10, null=True),
        ),
    ]
