# Generated by Django 5.1.4 on 2024-12-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_sending_disabled',
            field=models.BooleanField(default=True, help_text='Yarın Not olmasa bile E-posta gönderilsin'),
        ),
    ]
