# Generated by Django 5.1.4 on 2024-12-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_sending_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_sending_disabled',
            field=models.BooleanField(default=True, verbose_name='Yarın Not olmasa bile E-posta gönderilsin'),
        ),
    ]
