# Generated by Django 5.1.4 on 2025-01-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useractivitylog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useractivitylog',
            table='activity_logs',
        ),
    ]
