# Generated by Django 5.1.4 on 2025-01-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_useractivitylog_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secretary',
            table='secretaries',
        ),
    ]
