# Generated by Django 5.1.4 on 2024-12-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('master', 'Master Kullanıcı'), ('secretary', 'Sekreter')], default='master', max_length=10),
        ),
    ]
