# Generated by Django 5.1.4 on 2025-01-03 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_secretary_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hassecretaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
