# Generated by Django 5.1.4 on 2024-12-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_secretary_user_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secretary',
        ),
    ]
