# Generated by Django 5.1.4 on 2024-12-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_secretary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretary',
            name='user_account',
        ),
    ]
