version: "2.32.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfıle
    env_file:
      - SanalAjanda/docker.env
    ports:
      - "0.0.0.0:8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
volumes:
  static-data: