services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - sanalAjanda/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
volumes:
  static-data: