services:
  postgres:
    image: postgres:latest
    env_file:
      - sanalAjanda/docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    command: -p 5432
  app:
    container_name: app_sanalAjanda
    hostname: app_sanalAjanda
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - sanalAjanda/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8080:8080"
    command: gunicorn --workers 4 --timeout 60 --bind 0.0.0.0:8080 sanalAjanda.wsgi:application
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ajandanotdefteri@gmail.com -d sanalajanda.com -d www.sanalajanda.com --agree-tos
    entrypoint:
      - /bin/sh
      - -c
      - "trap exit TERM; while :; do certbot renew && sleep 10h & wait $${!}; done;"


volumes:
  postgresql-data:
  static-data: