services:
  postgres:
    image: postgres:latest
    env_file:
      - sanalAjanda/docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    command: -p 5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - sanalAjanda/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8080:8080"
    command: gunicorn sanalAjanda.wsgi:application --bind 0.0.0.0:8080

volumes:
  postgresql-data:
  static-data: