# Generated by Django 5.1.4 on 2024-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('question', models.CharField(blank=True, default='', max_length=254)),
                ('answer', models.CharField(blank=True, default='', max_length=254)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faq Setting',
                'verbose_name_plural': 'Faq Settings',
                'ordering': ('id', 'name', 'question', 'answer', 'updated_date'),
            },
        ),
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('description', models.CharField(blank=True, default='', max_length=254)),
                ('parameter', models.CharField(blank=True, default='', max_length=254)),
                ('link', models.CharField(blank=True, default='', max_length=254)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
                'ordering': ('id', 'name', 'description', 'parameter', 'link', 'updated_date', 'created_date'),
            },
        ),
        migrations.CreateModel(
            name='PricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=25)),
                ('parameter', models.CharField(blank=True, default='', max_length=25)),
                ('price', models.CharField(blank=True, default='', max_length=25)),
                ('feat1', models.CharField(blank=True, default='', max_length=50)),
                ('feat2', models.CharField(blank=True, default='', max_length=50)),
                ('feat3', models.CharField(blank=True, default='', max_length=50)),
                ('feat4', models.CharField(blank=True, default='', max_length=50)),
                ('feat5', models.CharField(blank=True, default='', max_length=50)),
                ('feat6', models.CharField(blank=True, default='', max_length=50)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Setting',
                'verbose_name_plural': 'Pricing Settings',
                'ordering': ('id', 'name', 'parameter', 'price', 'updated_date'),
            },
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ('id', 'name', 'description', 'parameter', 'updated_date', 'created_date'), 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
    ]
