# Generated by Django 5.1.4 on 2024-12-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imgupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('parameter', models.CharField(blank=True, default='', max_length=254)),
                ('link', models.CharField(blank=True, default='', max_length=254)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Navbar Setting',
                'verbose_name_plural': 'Navbar Settings',
                'ordering': ('id', 'name', 'parameter', 'link', 'updated_date', 'created_date'),
            },
        ),
    ]
