# Generated by Django 5.1.4 on 2025-01-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('order_number', models.CharField(max_length=50, verbose_name='Sipariş No')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Kredi Kartı'), ('bank_transfer', 'Banka Havalesi'), ('other', 'Diğer')], max_length=20, verbose_name='Ödeme Şekli')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödeme Tutarı')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
            ],
        ),
    ]
