# Generated by Django 5.1.4 on 2025-01-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
